# 📈 Stock Market Movement Prediction  
### A Data-Driven Analysis using Technical Indicators

## 🎯 Problem Statement

The objective is to analyze whether stock prices move **UP or DOWN** using technical indicators.

We aim to understand:
- Which indicators influence movement
- Whether combining indicators improves insight
- How market behavior can be interpreted using data

## 📊 Dataset Overview

We begin by inspecting the dataset structure and features.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/Users/deepanshus/StockMarketPredictor/Project/data/Combined/all/1.csv")  

df.head()

         rsi      macd  sma_ratio  volume_change  volatility    target
0  52.729384  5.231607   1.041503      -0.764616    0.015705 -0.009905
1  54.632972  5.343971   1.040495      -0.387146    0.015875  0.033691
2  68.850806  6.284495   1.044956       3.874652    0.015084 -0.028466
3  57.588533  6.152034   1.046341      -0.729922    0.018880 -0.012892
4  53.169572  5.627148   1.046767      -0.136228    0.019619  0.000297

## 🧹 Data Validation

We validate:
- Missing values
- Duplicate entries
- Data consistency

This ensures reliability before analysis.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55207 entries, 0 to 55206
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   rsi            52476 non-null  object
 1   macd           52471 non-null  object
 2   SMA Ratio      52436 non-null  float64
 3   volume_change  52465 non-null  float64
 4   volatility     52447 non-null  float64
 5   target         55207 non-null  float64
dtypes: float64(4), object(2)
memory usage: 2.5+ MB

In [7]:
df.isnull().sum()

rsi              2731
macd             2736
SMA Ratio        2771
volume_change    2742
volatility       2760
target              0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1838)

In [9]:
df.columns

Index(['rsi', 'macd', 'SMA Ratio', 'volume_change', 'volatility', 'target'], dtype='object')

In [10]:
df.rename(columns={'SMA Ratio': 'sma_ratio'}, inplace=True)

In [11]:
cols = ['rsi', 'macd', 'sma_ratio', 'volume_change', 'volatility']

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [12]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55207 entries, 0 to 55206
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   rsi            51924 non-null  float64
 1   macd           51919 non-null  float64
 2   sma_ratio      52436 non-null  float64
 3   volume_change  52465 non-null  float64
 4   volatility     52447 non-null  float64
 5   target         55207 non-null  float64
dtypes: float64(6)
memory usage: 2.5 MB

rsi              3283
macd             3288
sma_ratio        2771
volume_change    2742
volatility       2760
target              0
dtype: int64

In [13]:
df.fillna(method='ffill', inplace=True)
df.fillna(method='bfill', inplace=True)

/var/folders/g8/43rm_8rs5wbchfhhkxt_832c0000gn/T/ipykernel_87884/3964524321.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)
/var/folders/g8/43rm_8rs5wbchfhhkxt_832c0000gn/T/ipykernel_87884/3964524321.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', inplace=True)

In [14]:
df = df.drop_duplicates()

In [15]:
df = df[df['volatility'] >= 0]

In [16]:
for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    df = df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]

In [17]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 33907 entries, 0 to 55203
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   rsi            33907 non-null  float64
 1   macd           33907 non-null  float64
 2   sma_ratio      33907 non-null  float64
 3   volume_change  33907 non-null  float64
 4   volatility     33907 non-null  float64
 5   target         33907 non-null  float64
dtypes: float64(6)
memory usage: 1.8 MB

,rsi,macd,sma_ratio,volume_change,volatility,target
count,33907.000000,33907.000000,33907.000000,33907.000000,33907.000000,33907.000000
mean,51.303468,2.466071,1.008517,0.019846,0.026803,0.001523
std,15.066590,15.839097,0.047490,0.476744,0.022229,0.044752
min,13.626647,-42.153425,0.877841,-1.381381,0.003050,-0.601866
25%,41.401349,-3.969438,0.976662,-0.322140,0.012284,-0.010445
50%,50.983213,0.568125,1.006863,-0.058424,0.017823,0.000164
75%,61.310538,8.610587,1.039625,0.285215,0.030514,0.011194
max,90.016768,51.372267,1.142256,1.490001,0.098241,0.795685