In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("/Users/deepanshus/StockMarketPredictor/Project/data/Combined/all/1.csv")

In [3]:
df.head()

         rsi      macd  sma_ratio  volume_change  volatility    target
0  52.729384  5.231607   1.041503      -0.764616    0.015705 -0.009905
1  54.632972  5.343971   1.040495      -0.387146    0.015875  0.033691
2  68.850806  6.284495   1.044956       3.874652    0.015084 -0.028466
3  57.588533  6.152034   1.046341      -0.729922    0.018880 -0.012892
4  53.169572  5.627148   1.046767      -0.136228    0.019619  0.000297

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(df[['rsi','macd','sma_ratio','volume_change','volatility']])

In [9]:
df.corr()['target'].sort_values(ascending=False)
X = df[['rsi','macd','sma_ratio','volume_change','volatility']]
y = (df['target'] > 0).astype(int)

In [12]:
from sklearn.ensemble import RandomForestClassifier

temp_model = RandomForestClassifier()
temp_model.fit(X, y)

importances = temp_model.feature_importances_

for name, score in zip(X.columns, importances):
    print(name, score)

rsi 0.2023920033144652
macd 0.20340782736275725
sma_ratio 0.19744425449290912
volume_change 0.19728200496623574
volatility 0.19947390986363273

In [13]:
df.corr()['target'].sort_values()

macd            -0.205279
rsi             -0.140928
sma_ratio       -0.105668
volume_change    0.006657
volatility       0.049568
target           1.000000
Name: target, dtype: float64

In [14]:
df['rsi_macd'] = df['rsi'] * df['macd']

In [15]:
df[['rsi_macd','target']].corr()

          rsi_macd    target
rsi_macd  1.000000 -0.171171
target   -0.171171  1.000000